version: '3.8'

services:
  binance-bot:
    build: .
    image: alexanderloong/binance-bot:v1.0.3
    container_name: binance_bot
    restart: always # Auto-restart on crash or system reboot
    volumes:
      - .:/app # Mount current dir to save logs back to host
    env_file:
      - .env
    environment:
      - TZ=Asia/Ho_Chi_Minh
    # network_mode: "host" # Uncomment if improved network performance is needed
